# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  sync:
    desc: Sync dependencies
    cmds:
      - uv sync

  lint:
    desc: Lint the codebase
    cmds:
      - uv run ruff check {{.CLI_ARGS}}

  format:
    desc: Format the codebase
    cmds:
      - uv run ruff format {{.CLI_ARGS}}

  typecheck:
    desc: Typecheck the codebase
    cmds:
      - uv run mypy

  check:
    desc: Lint, Format, Typecheck
    cmds:
      - task lint -- --fix
      - task format
      - task typecheck

  ci:
    desc: Lint, Format, Typecheck (without modifying codebase)
    deps:
      - task: lint
      - task: format
        vars:
          CLI_ARGS: --check
      - task: typecheck

  update_app:
    desc: Update Poke-Controller Modified Extension
    cmds:
      - uv run ./scripts/update_app.py

  setup_dev:
    desc: Setup development environment
    cmds:
      - git config core.hooksPath .githooks

  app:
    vars:
      PROFILE: '{{.PROFILE|default "default"}}'
      DEV: '{{.DEV|default false}}'
    cmds:
      - task update_app
      - task sync
      - |
        cd SerialController
        {{ if eq .DEV "true" }}
        uv run python -X dev -- Window.py --profile {{.PROFILE}}
        {{ else }}
        uv run python -- Window.py --profile {{.PROFILE}}
        {{ end }}
