# for compatibility
from pokecontrollerext.api.v0_1_8.command.commands.unit import (  # noqa
    UnitCommand as UnitCommand,
    A as A,
    B as B,
    X as X,
    Y as Y,
    L as L,
    R as R,
    ZL as ZL,
    ZR as ZR,
    MINUS as MINUS,
    PLUS as PLUS,
    LCLICK as LCLICK,
    RCLICK as RCLICK,
    HOME as HOME,
    CAPTURE as CAPTURE,
    UP as UP,
    UP_RIGHT as UP_RIGHT,
    RIGHT as RIGHT,
    DOWN_RIGHT as DOWN_RIGHT,
    DOWN as DOWN,
    DOWN_LEFT as DOWN_LEFT,
    LEFT as LEFT,
    UP_LEFT as UP_LEFT,
)
